projects:
  database:
    schemaPath: src/prisma/prisma.graphql
    extensions:
      prisma: "prisma1/prisma.yml"
      endpoints:
        default: "${env:PRISMA_ENDPOINT}"
      codegen:
        - generator: prisma-binding
          language: typescript
          output:
            binding: src/prisma/prisma.binding.ts
