projects:
  database:
    schemaPath: src/prisma/prisma.graphql
    extensions:
      prisma: "prisma.yml"
      endpoints:
        default: https://monsoon-prisma-staging.herokuapp.com/monsoon/staging
      codegen:
        - generator: prisma-binding
          language: typescript
          output:
            binding: src/prisma/prisma.binding.ts
