service: monsoon-test
app: myapp
org: frahman5

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
# frameworkVersion: "=X.X.X"

plugins:
  - serverless-plugin-typescript
  - serverless-offline
  - serverless-dotenv-plugin
  - serverless-plugin-include-dependencies

provider:
  name: aws
  runtime: nodejs10.x

package:
  include:
    - src/**/*.graphql

functions:
  checkAndAuthorizeUsers:
    handler: src/handler.checkAndAuthorizeUsers
    events:
      - http:
          path: api/checkAndAuthorize
          method: post
          integration: lambda
          cors: true
