service: authorize-users
app: monsoon
org: seasons

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
# frameworkVersion: "=X.X.X"

plugins:
  - serverless-plugin-typescript
  - serverless-offline
  - serverless-dotenv-plugin

provider:
  name: aws
  runtime: nodejs10.x

package:
  exclude:
    - src/**
    - node_modules/**
    - webhooks
  include:
    - src/handler.ts
    - src/prisma/**
    - scripts/**

functions:
  checkAndAuthorizeUsers:
    handler: src/handler.checkAndAuthorizeUsers
    events:
      - schedule: rate(1 minute)
