service: monsoon
app: monsoon
org: seasons

# Pin to 1.59.3 because 1.60.0 breaks the build
frameworkVersion: "=1.59.3"

plugins:
  - serverless-plugin-typescript
  - serverless-offline
  - serverless-dotenv-plugin

provider:
  name: aws
  runtime: nodejs10.x

package:
  exclude:
    - node_modules/flow-bin/**
    - node_modules/detective-typescript/**
    - node_modules/@nestjs/**
    - node_modules/@angular-devkit/**
    - node_modules/typescript/**
    - node_modules/aws-sdk/**
  include:
    - src/schema.graphql
    - src/handler.ts
    - src/prisma/**
    - src/airtable/**
    - master-email.html

functions:
  checkAndAuthorizeUsers:
    handler: src/cron/checkAndAuthorizeUsers.checkAndAuthorizeUsers
    events:
      - schedule: rate(1 minute)
  syncPhysicalProductAndReservationStatus:
    handler: src/cron/syncPhysicalProductAndReservationStatus.run
    events:
      - schedule: rate(1 minute)
    timeout: 60 # rather than default of 6
  sendReservationReturnNotifications:
    handler: src/cron/sendReturnNotifications.sendReturnNotifications
    events:
      - schedule: rate(6 hours)
    timeout: 60
  airtablePrismaSyncHealth:
    handler: src/cron/reportAirtablePrismaSyncHealth.run
    events:
      - schedule: cron(0 14 ? * MON-FRI *) # 2pm UTC, 9AM EST, every monday to friday
    timeout: 60
