service: monsoon
app: monsoon
org: l2succes

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
# frameworkVersion: "=X.X.X"

plugins:
  - serverless-plugin-typescript
  - serverless-offline
  - serverless-dotenv-plugin
  - serverless-plugin-include-dependencies

provider:
  name: aws
  runtime: nodejs10.x

package:
  include:
    - src/**/*.graphql

functions:
  graphql:
    handler: src/handler.graphql
    events:
      - http:
          path: /
          method: post
          cors: true
      - http:
          path: /
          method: get
          cors: true
  playground:
    handler: src/handler.graphql
    events:
      - http:
          path: playground
          method: get
          cors: true
  postgraphile:
    handler: src/postgraphile.graphql
    events:
      - http:
          path: /postgraphile
          method: post
          cors: true
      - http:
          path: /postgraphile
          method: get
          cors: true
