service: monsoon
app: monsoon
org: seasons

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
# frameworkVersion: "=X.X.X"

plugins:
  - serverless-plugin-typescript
  - serverless-offline
  - serverless-dotenv-plugin

provider:
  name: aws
  runtime: nodejs10.x

package:
  include:
    - src/schema.graphql
    - src/handler.ts
    - src/prisma/**

functions:
  checkAndAuthorizeUsers:
    handler: src/handler.checkAndAuthorizeUsers
    events:
      - schedule: rate(1 minute)
  syncPhysicalProductAndReservationStatus:
    handler: src/cron/syncPhysicalProductAndReservationStatus.syncPhysicalProductAndReservationStatus
    events:
      - schedule: rate(1 minute)
    timeout: 60 # timeout in 60 seconds, rather than default of 6
