service: monsoon
app: monsoon
org: seasons

# Pin to 1.59.3 because 1.60.0 breaks the build
# frameworkVersion: "=1.59.3"

plugins:
  - serverless-plugin-typescript
  - serverless-offline
  - serverless-dotenv-plugin

provider:
  name: aws
  runtime: nodejs10.x

package:
  exclude:
    - node_modules/flow-bin/**
    - node_modules/detective-typescript/**
    - node_modules/typescript/**
    - node_modules/aws-sdk/**
  include:
    - src/schema.graphql
    - src/handler.ts
    - src/prisma/**
    - src/airtable/**

functions:
  checkAndAuthorizeUsers:
    handler: src/handler.checkAndAuthorizeUsers
    events:
      - schedule: rate(1 minute)
  syncPhysicalProductAndReservationStatus:
    handler: src/cron/syncPhysicalProductAndReservationStatus.syncPhysicalProductAndReservationStatus
    events:
      - schedule: rate(1 minute)
    timeout: 60 # timeout in 60 seconds, rather than default of 6
