version: 2.1

orbs:
  node: circleci/node@4.6.0
  docker: circleci/docker@1.6.0

jobs:
  test-unit:
    machine:
      image: ubuntu-2004:202107-02

    working_directory: ~/monsoon

    steps:
      - checkout

      - node/install:
          node-version: "14.17.1"
          install-yarn: true

      - node/install-packages:
          pkg-manager: yarn

      - docker/install-docker

      - run:
          name: Start up docker containers
          command: docker-compose up -d

      - run:
          name: Initialize monsoon$dev schema
          command: yarn prisma migrate deploy

      - run:
          name: Install postgres tools
          command: sudo apt update && sudo apt install postgresql

      - run:
          name: Clone staging data into local Postgres DB
          command: node bin/cli.js spp local staging -f

      - run:
          name: Install JUnit coverage reporter
          command: yarn add --dev jest-junit

      - run:
          name: Run unit tests
          command: yarn test --verbose

      - store_test_results:
          path: ./reports/junit/

      - store_artifacts:
          path: ./reports/junit

  test-integration:
    machine:
      image: ubuntu-2004:202107-02

    working_directory: ~/monsoon

    steps:
      - checkout

      - node/install:
          node-version: "14.17.1"
          install-yarn: true

      - docker/install-docker

      - run:
          name: Start up docker containers
          command: docker-compose up -d

      - node/install-packages:
          pkg-manager: yarn

      - run:
          name: Initialize monsoon$dev schema
          command: yarn prisma migrate deploy

      - run:
          name: Install postgres tools
          command: sudo apt update && sudo apt install postgresql

      - run:
          name: Clone staging data into local Postgres DB
          command: node bin/cli.js spp local staging -f

      - run:
          name: Generate user for integration test
          command: node bin/cli.js ctu --email integration_test_ci@seasons.nyc --password Seasons2020 --prisma local --roles Customer Admin --aid 60e4ac2aaf20ac0069155156 --dbo

      - run:
          name: Install JUnit coverage reporter
          command: yarn add --dev jest-junit

      - run:
          name: Start server locally to run integration tests against
          command: yarn ci

      - run:
          name: Wait for server to spin up
          command: sleep 200

      - run:
          name: Run integration test suite
          command: yarn test:e2e:ci
          environment:
            JEST_JUNIT_OUTPUT_DIR: ./reports/junit/

      # https://circleci.com/docs/2.0/collect-test-data/#jest
      - store_test_results:
          path: ./reports/junit/

      - store_artifacts:
          path: ./reports/junit

      - store_artifacts:
          path: ./nohup.out

workflows:
  run_all_tests:
    jobs:
      - test-unit
      - test-integration
