version: 2.1

orbs:
  node: circleci/node@4.6.0
  docker: circleci/docker@1.6.0

jobs:
  test-unit:
    machine: true

    working_directory: ~/monsoon

    steps:
      - checkout

      - node/install:
          node-version: "14.17.1"
          install-yarn: true

      - node/install-packages:
          pkg-manager: yarn

      - run:
          command: docker-compose up -d
          name: Start up docker containers

      - run:
          command: sleep 20
          name: Wait for containers to fully spin up

      - run:
          command: yarn test
          name: Run unit tests

  test-integration:
    docker:
      - image: postgres:12.6
    working_directory: ~/monsoon
    steps:
      - run:
          name: Gain sudo
          command: |
            apt-get update && apt-get install -y sudo && rm -rf /var/lib/apt/lists/*

      - run:
          name: Install curl, git, jq
          command: |
            sudo apt update
            sudo apt install curl -y
            sudo apt install git -y
            sudo apt-get install jq -y

      - checkout

      - docker/install-docker

      - docker/install-docker-compose

      - setup_remote_docker:
          version: 20.10.6
          docker_layer_caching: true

      - run:
          name: Start up docker containers
          command: docker-compose up -d

      - node/install:
          node-version: "14.17.1"
          install-yarn: true

      - node/install-packages:
          pkg-manager: yarn

      - run:
          command: sleep 20
          name: Wait for containers to fully spin up

      - run:
          command: node bin/cli.js spp local staging -f
          name: Clone staging data into local Postgres DB

      - run:
          command: node bin/cli.js ctu --email integration_test_ci@seasons.nyc --password Seasons2020 --prisma local --roles Customer Admin --aid 60e4ac2aaf20ac0069155156 --dbo
          name: Generate user for integration test

      - run:
          command: node scripts/esbuild.watcher.js
          name: Start server locally to run integration tests against

      - run:
          command: sleep 20
          name: Wait for server to spin up

      - run:
          command: yarn test:e2e
          name: Run integration test suite

workflows:
  run_all_tests:
    jobs:
      - test-unit
      - test-integration
