version: 2.1

jobs:
  test-unit:
    docker:
      - image: cimg/node:14.17.1

    working_directory: ~/monsoon

    steps:
      - checkout

      - run:
          command: yarn
          name: Install dependencies

      - run:
          command: docker-compose up -d
          name: Start up docker containers

      - run:
          command: sleep 20
          name: Wait for containers to fully spin up

      - run:
          command: yarn prisma:deploy
          name: Deploy Prisma service

      - run:
          command: yarn test
          name: Run unit tests

  test-integration:
    docker:
      - image: postgres:12.6
        auth:
          username: dmonay
          password: $DOCKERHUB_PASSWORD # context / project UI env-var reference
    working_directory: ~/monsoon
    steps:
      - checkout

      - run:
          name: Update and install curl
          command: |
            apt update &&  apt upgrade -y
            apt install curl -y

      - run:
          name: Install Node
          command: |
            curl -sL https://deb.nodesource.com/setup_14.x | bash -
            apt install nodejs -y

      - run:
          name: Install Yarn
          command: |
            curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
            echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list
            apt update
            apt install yarn -y

      - run:
          command: yarn
          name: Install dependencies

      - run:
          name: Install Docker
          command: |
            apt-get install apt-transport-https ca-certificates curl gnupg2 software-properties-common -y
            curl -fsSL https://download.docker.com/linux/debian/gpg | apt-key add -
            add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/debian buster stable"
            apt-get update
            apt-get install docker-ce docker-ce-cli containerd.io -y

      - run:
          name: Install docker-compose
          command: |
            curl -L https://github.com/docker/compose/releases/download/1.29.2/docker-compose-`uname -s`-`uname -m` -o /usr/local/bin/docker-compose
            chmod +x /usr/local/bin/docker-compose

      - run:
          command: docker-compose up -d
          name: Start up docker containers

      - run:
          command: sleep 20
          name: Wait for containers to fully spin up

      - run:
          command: yarn prisma:deploy
          name: Deploy Prisma service

      - run:
          command: yarn build
          name: Compile so we can run the next cmd

      - run:
          command: node bin/cli.js spp local staging -f
          name: Clone staging data into local Postgres DB

      - run:
          command: node bin/cli.js ctu --email integration_test_ci@seasons.nyc --password Seasons2020 --prisma local --roles Customer Admin --aid 60e4ac2aaf20ac0069155156 --dbo
          name: Generate user for integration test

      - run:
          command: node scripts/esbuild.watcher.js
          name: Start server locally to run integration tests against

      - run:
          command: sleep 20
          name: Wait for server to spin up

      - run:
          command: yarn test:e2e
          name: Run integration test suite

workflows:
  run_all_tests:
    jobs:
      - test-unit
      - test-integration
