# Javascript Node CircleCI 2.1 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1

orbs:
  node: circleci/node@4.5.1
  docker: circleci/docker@1.6.0

jobs:
  test-unit:
    machine: true
    working_directory: ~/monsoon
    steps:
      - checkout

      - run:
          name: Install Node Version Manager
          command: |
            curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.11/install.sh | bash
            export NVM_DIR="/opt/circleci/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"
            nvm install v16.4.0
            nvm alias default v16.4.0
            echo 'export NVM_DIR="/opt/circleci/.nvm"' >> $BASH_ENV
            echo "[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"" >> $BASH_ENV

      - node/install-yarn

      - node/install-packages:
          pkg-manager: yarn

      - docker/install-docker

      - docker/install-docker-compose

      - run:
          command: docker-compose up -d
          name: Start up docker containers

      - run:
          command: yarn prisma1 deploy
          name: Deploy Prisma1 service

      - run:
          command: yarn jest --verbose -i
          name: Run unit tests

workflows:
  run_unit_tests:
    jobs:
      - test-unit
