# Javascript Node CircleCI 2.1 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1
orbs:
  node: circleci/node@4.5.1
jobs:
  test-unit:
    executor:
      name: node/default
      tag: "12.18.1"
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: docker-compose up -d
          name: Start up docker containers
      - run:
          command: yarn prisma1 deploy
          name: Deploy Prisma1 service
      - run:
          command: yarn jest --verbose -i
          name: Run unit tests
workflows:
  run_unit_tests:
    jobs:
      - test-unit
