"use strict"
// Code generated by Prisma (prisma@1.34.10). DO NOT EDIT.
// Please don't change this file manually but run `prisma generate` to update it.
// For more information, please read the docs: https://www.prisma.io/docs/prisma-client/
exports.__esModule = true
exports.prisma = exports.Prisma = exports.models = void 0
var prisma_client_lib_1 = require("prisma-client-lib")
var prisma_schema_1 = require("./prisma-schema")
/**
 * Model Metadata
 */
exports.models = [
  {
    name: "ProductTierName",
    embedded: false,
  },
  {
    name: "BrandTier",
    embedded: false,
  },
  {
    name: "Department",
    embedded: false,
  },
  {
    name: "LocationType",
    embedded: false,
  },
  {
    name: "CustomerStatus",
    embedded: false,
  },
  {
    name: "UserRole",
    embedded: false,
  },
  {
    name: "InventoryStatus",
    embedded: false,
  },
  {
    name: "PhysicalProductStatus",
    embedded: false,
  },
  {
    name: "PhysicalProductOffloadMethod",
    embedded: false,
  },
  {
    name: "ProductStatus",
    embedded: false,
  },
  {
    name: "ReservationStatus",
    embedded: false,
  },
  {
    name: "BagItemStatus",
    embedded: false,
  },
  {
    name: "Plan",
    embedded: false,
  },
  {
    name: "ProductType",
    embedded: false,
  },
  {
    name: "BottomSizeType",
    embedded: false,
  },
  {
    name: "QuestionType",
    embedded: false,
  },
  {
    name: "Rating",
    embedded: false,
  },
  {
    name: "LetterSize",
    embedded: false,
  },
  {
    name: "ProductArchitecture",
    embedded: false,
  },
  {
    name: "WarehouseLocationType",
    embedded: false,
  },
  {
    name: "PhotographyStatus",
    embedded: false,
  },
  {
    name: "EmailId",
    embedded: false,
  },
  {
    name: "PackageTransitEventStatus",
    embedded: false,
  },
  {
    name: "PackageTransitEventSubStatus",
    embedded: false,
  },
  {
    name: "ReservationPhase",
    embedded: false,
  },
  {
    name: "UserPushNotificationInterestType",
    embedded: false,
  },
  {
    name: "InAdmissableReason",
    embedded: false,
  },
  {
    name: "ShippingCode",
    embedded: false,
  },
  {
    name: "ExternalShopifyIntegration",
    embedded: false,
  },
  {
    name: "Brand",
    embedded: false,
  },
  {
    name: "Category",
    embedded: false,
  },
  {
    name: "Color",
    embedded: false,
  },
  {
    name: "Collection",
    embedded: false,
  },
  {
    name: "CollectionPlacement",
    embedded: false,
  },
  {
    name: "Image",
    embedded: false,
  },
  {
    name: "Location",
    embedded: false,
  },
  {
    name: "Tag",
    embedded: false,
  },
  {
    name: "Product",
    embedded: false,
  },
  {
    name: "ProductTier",
    embedded: false,
  },
  {
    name: "Season",
    embedded: false,
  },
  {
    name: "ProductSeason",
    embedded: false,
  },
  {
    name: "ProductMaterialCategory",
    embedded: false,
  },
  {
    name: "ProductModel",
    embedded: false,
  },
  {
    name: "ProductFunction",
    embedded: false,
  },
  {
    name: "ProductVariantPrice",
    embedded: false,
  },
  {
    name: "ShopifyProductVariant",
    embedded: false,
  },
  {
    name: "ProductVariant",
    embedded: false,
  },
  {
    name: "PhysicalProductPrice",
    embedded: false,
  },
  {
    name: "PhysicalProductDamageType",
    embedded: false,
  },
  {
    name: "PhysicalProductQualityReport",
    embedded: false,
  },
  {
    name: "PhysicalProduct",
    embedded: false,
  },
  {
    name: "ProductNotification",
    embedded: false,
  },
  {
    name: "ProductFit",
    embedded: false,
  },
  {
    name: "ProductNotificationType",
    embedded: false,
  },
  {
    name: "WarehouseLocationConstraint",
    embedded: false,
  },
  {
    name: "WarehouseLocation",
    embedded: false,
  },
  {
    name: "PaymentPlan",
    embedded: false,
  },
  {
    name: "PaymentPlanTier",
    embedded: false,
  },
  {
    name: "EmailReceipt",
    embedded: false,
  },
  {
    name: "SmsStatus",
    embedded: false,
  },
  {
    name: "SmsReceipt",
    embedded: false,
  },
  {
    name: "PushNotificationReceipt",
    embedded: false,
  },
  {
    name: "SeasonCode",
    embedded: false,
  },
  {
    name: "SeasonString",
    embedded: false,
  },
  {
    name: "UserVerificationMethod",
    embedded: false,
  },
  {
    name: "UserVerificationStatus",
    embedded: false,
  },
  {
    name: "PushNotificationStatus",
    embedded: false,
  },
  {
    name: "FitPicStatus",
    embedded: false,
  },
  {
    name: "FitPic",
    embedded: false,
  },
  {
    name: "FitPicReportStatus",
    embedded: false,
  },
  {
    name: "FitPicReport",
    embedded: false,
  },
  {
    name: "InterestedUser",
    embedded: false,
  },
  {
    name: "User",
    embedded: false,
  },
  {
    name: "StylePreferences",
    embedded: false,
  },
  {
    name: "CustomerStyle",
    embedded: false,
  },
  {
    name: "CustomerDetail",
    embedded: false,
  },
  {
    name: "BagItem",
    embedded: false,
  },
  {
    name: "CustomerAdmissionsData",
    embedded: false,
  },
  {
    name: "UTMData",
    embedded: false,
  },
  {
    name: "Customer",
    embedded: false,
  },
  {
    name: "CustomerMembership",
    embedded: false,
  },
  {
    name: "PauseRequest",
    embedded: false,
  },
  {
    name: "RecentlyViewedProduct",
    embedded: false,
  },
  {
    name: "Reservation",
    embedded: false,
  },
  {
    name: "ReservationFeedback",
    embedded: false,
  },
  {
    name: "ProductVariantFeedback",
    embedded: false,
  },
  {
    name: "ProductVariantFeedbackQuestion",
    embedded: false,
  },
  {
    name: "ReservationReceipt",
    embedded: false,
  },
  {
    name: "ReservationReceiptItem",
    embedded: false,
  },
  {
    name: "UserPushNotificationInterest",
    embedded: false,
  },
  {
    name: "UserPushNotification",
    embedded: false,
  },
  {
    name: "Package",
    embedded: false,
  },
  {
    name: "PackageTransitEvent",
    embedded: false,
  },
  {
    name: "ShippingMethod",
    embedded: false,
  },
  {
    name: "ShippingOption",
    embedded: false,
  },
  {
    name: "Label",
    embedded: false,
  },
  {
    name: "BillingInfo",
    embedded: false,
  },
  {
    name: "ProductRequest",
    embedded: false,
  },
  {
    name: "ProductVariantWant",
    embedded: false,
  },
  {
    name: "TopSize",
    embedded: false,
  },
  {
    name: "BottomSize",
    embedded: false,
  },
  {
    name: "Size",
    embedded: false,
  },
  {
    name: "ActiveAdminUser",
    embedded: false,
  },
  {
    name: "AdminAction",
    embedded: false,
  },
  {
    name: "AdminActionLog",
    embedded: false,
  },
  {
    name: "SyncTimingType",
    embedded: false,
  },
  {
    name: "SyncTiming",
    embedded: false,
  },
]
/**
 * Type Defs
 */
exports.Prisma = prisma_client_lib_1.makePrismaClientClass({
  typeDefs: prisma_schema_1.typeDefs,
  models: exports.models,
  endpoint: "" + process.env["PRISMA_ENDPOINT"],
  secret: "" + process.env["PRISMA_SECRET"],
})
exports.prisma = new exports.Prisma()
