ALTER TABLE "monsoon$dev"."BlogPost" ALTER COLUMN "createdAt" SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "monsoon$dev"."Brand" ALTER COLUMN "createdAt" SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "monsoon$dev"."Collection" ALTER COLUMN "createdAt" SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "monsoon$dev"."Image" ALTER COLUMN "createdAt" SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "monsoon$dev"."Location" ALTER COLUMN "createdAt" SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "monsoon$dev"."Tag" ALTER COLUMN "createdAt" SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "monsoon$dev"."Product" ALTER COLUMN "createdAt" SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "monsoon$dev"."ProductTier" ALTER COLUMN "createdAt" SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "monsoon$dev"."ProductVariant" ALTER COLUMN "createdAt" SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "monsoon$dev"."PhysicalProductQualityReport" ALTER COLUMN "createdAt" SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "monsoon$dev"."PhysicalProduct" ALTER COLUMN "createdAt" SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "monsoon$dev"."ProductNotification" ALTER COLUMN "createdAt" SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "monsoon$dev"."WarehouseLocationConstraint" ALTER COLUMN "createdAt" SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "monsoon$dev"."WarehouseLocation" ALTER COLUMN "createdAt" SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "monsoon$dev"."PaymentPlan" ALTER COLUMN "createdAt" SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "monsoon$dev"."EmailReceipt" ALTER COLUMN "createdAt" SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "monsoon$dev"."SmsReceipt" ALTER COLUMN "sentAt" SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "monsoon$dev"."PushNotificationReceipt" ALTER COLUMN "createdAt" SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "monsoon$dev"."FitPic" ALTER COLUMN "createdAt" SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "monsoon$dev"."FitPicReport" ALTER COLUMN "reportedAt" SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "monsoon$dev"."InterestedUser" ALTER COLUMN "createdAt" SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "monsoon$dev"."User" ALTER COLUMN "createdAt" SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "monsoon$dev"."CustomerDetail" ALTER COLUMN "createdAt" SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "monsoon$dev"."BagItem" ALTER COLUMN "createdAt" SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "monsoon$dev"."CustomerAdmissionsData" ALTER COLUMN "createdAt" SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "monsoon$dev"."UTMData" ALTER COLUMN "createdAt" SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "monsoon$dev"."Customer" ALTER COLUMN "createdAt" SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "monsoon$dev"."CustomerNotificationBarReceipt" ALTER COLUMN "createdAt" SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "monsoon$dev"."CustomerMembershipSubscriptionData" ALTER COLUMN "createdAt" SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "monsoon$dev"."PauseRequest" ALTER COLUMN "createdAt" SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "monsoon$dev"."RecentlyViewedProduct" ALTER COLUMN "createdAt" SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "monsoon$dev"."OrderLineItem" ALTER COLUMN "createdAt" SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "monsoon$dev"."Order" ALTER COLUMN "createdAt" SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "monsoon$dev"."Reservation" ALTER COLUMN "createdAt" SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "monsoon$dev"."ReservationFeedback" ALTER COLUMN "createdAt" SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "monsoon$dev"."ReservationReceipt" ALTER COLUMN "createdAt" SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "monsoon$dev"."Package" ALTER COLUMN "createdAt" SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "monsoon$dev"."PackageTransitEvent" ALTER COLUMN "createdAt" SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "monsoon$dev"."ShippingMethod" ALTER COLUMN "createdAt" SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "monsoon$dev"."ShippingOption" ALTER COLUMN "createdAt" SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "monsoon$dev"."BillingInfo" ALTER COLUMN "createdAt" SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "monsoon$dev"."SyncTiming" ALTER COLUMN "createdAt" SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "monsoon$dev"."Launch" ALTER COLUMN "createdAt" SET DEFAULT CURRENT_TIMESTAMP;


--Add missing `DEFAULT` constraints to the database
--https://pris.ly/d/schema-incompatibilities#default-values-arent-represented-in-database

ALTER TABLE "monsoon$dev"."Brand" ALTER COLUMN "isPrimaryBrand" SET DEFAULT false;
ALTER TABLE "monsoon$dev"."Brand" ALTER COLUMN "published" SET DEFAULT true;
ALTER TABLE "monsoon$dev"."Brand" ALTER COLUMN "featured" SET DEFAULT false;
ALTER TABLE "monsoon$dev"."Category" ALTER COLUMN "visible" SET DEFAULT false;
ALTER TABLE "monsoon$dev"."Collection" ALTER COLUMN "displayTextOverlay" SET DEFAULT false;
ALTER TABLE "monsoon$dev"."Collection" ALTER COLUMN "published" SET DEFAULT false;
ALTER TABLE "monsoon$dev"."Product" ALTER COLUMN "buyNewEnabled" SET DEFAULT false;
ALTER TABLE "monsoon$dev"."Product" ALTER COLUMN "status" SET DEFAULT 'Available';
ALTER TABLE "monsoon$dev"."PhysicalProductPrice" ALTER COLUMN "buyUsedEnabled" SET DEFAULT false;
ALTER TABLE "monsoon$dev"."PhysicalProduct" ALTER COLUMN "barcoded" SET DEFAULT false;
ALTER TABLE "monsoon$dev"."ProductNotification" ALTER COLUMN "shouldNotify" SET DEFAULT true;
ALTER TABLE "monsoon$dev"."FitPic" ALTER COLUMN "includeInstagramHandle" SET DEFAULT false;
ALTER TABLE "monsoon$dev"."FitPic" ALTER COLUMN "status" SET DEFAULT 'Submitted';
ALTER TABLE "monsoon$dev"."FitPicReport" ALTER COLUMN "status" SET DEFAULT 'Pending';
ALTER TABLE "monsoon$dev"."User" ALTER COLUMN "role" SET DEFAULT 'Customer';
ALTER TABLE "monsoon$dev"."User" ALTER COLUMN "pushNotificationStatus" SET DEFAULT 'Denied';
ALTER TABLE "monsoon$dev"."User" ALTER COLUMN "sendSystemEmails" SET DEFAULT true;
ALTER TABLE "monsoon$dev"."User" ALTER COLUMN "verificationStatus" SET DEFAULT 'Pending';
ALTER TABLE "monsoon$dev"."User" ALTER COLUMN "verificationMethod" SET DEFAULT 'None';
ALTER TABLE "monsoon$dev"."CustomerDetail" ALTER COLUMN "insureShipment" SET DEFAULT false;
ALTER TABLE "monsoon$dev"."CustomerAdmissionsData" ALTER COLUMN "allAccessEnabled" SET DEFAULT true;
ALTER TABLE "monsoon$dev"."CustomerNotificationBarReceipt" ALTER COLUMN "viewCount" SET DEFAULT 0;
ALTER TABLE "monsoon$dev"."CustomerNotificationBarReceipt" ALTER COLUMN "clickCount" SET DEFAULT 0;
ALTER TABLE "monsoon$dev"."PauseRequest" ALTER COLUMN "pauseType" SET DEFAULT 'WithoutItems';
ALTER TABLE "monsoon$dev"."PauseRequest" ALTER COLUMN "notified" SET DEFAULT false;
ALTER TABLE "monsoon$dev"."RecentlyViewedProduct" ALTER COLUMN "viewCount" SET DEFAULT 0;
ALTER TABLE "monsoon$dev"."Order" ALTER COLUMN "status" SET DEFAULT 'Drafted';
ALTER TABLE "monsoon$dev"."Order" ALTER COLUMN "paymentStatus" SET DEFAULT 'NotPaid';
ALTER TABLE "monsoon$dev"."UserPushNotificationInterest" ALTER COLUMN "status" SET DEFAULT true;
ALTER TABLE "monsoon$dev"."UserPushNotification" ALTER COLUMN "status" SET DEFAULT true;
ALTER TABLE "monsoon$dev"."Launch" ALTER COLUMN "published" SET DEFAULT false;


--Fix 1-1 relations by adding `UNIQUE` constraints
--https://pris.ly/d/schema-incompatibilities#inline-1-1-relations-are-recognized-as-1-n-missing-unique-constraint

ALTER TABLE "monsoon$dev"."ShopifyProductVariant" ADD UNIQUE ("productVariant");
ALTER TABLE "monsoon$dev"."CustomerAdmissionsData" ADD UNIQUE ("customer");
ALTER TABLE "monsoon$dev"."UTMData" ADD UNIQUE ("customer");
ALTER TABLE "monsoon$dev"."CustomerMembership" ADD UNIQUE ("customer");
ALTER TABLE "monsoon$dev"."ReservationReceipt" ADD UNIQUE ("reservation");
ALTER TABLE "monsoon$dev"."AdminActionLogInterpretation" ADD UNIQUE ("log");


--Migrate IDs from varchar(25) to varchar(30)
--https://pris.ly/d/schema-incompatibilities#mismatching-cuid-length

ALTER TABLE "monsoon$dev"."ActiveAdminUser" ALTER COLUMN "id" SET DATA TYPE character varying(30);
ALTER TABLE "monsoon$dev"."ActiveAdminUser" ALTER COLUMN "admin" SET DATA TYPE character varying(30);
ALTER TABLE "monsoon$dev"."AdminActionLog" ALTER COLUMN "activeAdminUser" SET DATA TYPE character varying(30);
ALTER TABLE "monsoon$dev"."AdminActionLogInterpretation" ALTER COLUMN "id" SET DATA TYPE character varying(30);
ALTER TABLE "monsoon$dev"."BagItem" ALTER COLUMN "id" SET DATA TYPE character varying(30);
ALTER TABLE "monsoon$dev"."BagItem" ALTER COLUMN "customer" SET DATA TYPE character varying(30);
ALTER TABLE "monsoon$dev"."BagItem" ALTER COLUMN "productVariant" SET DATA TYPE character varying(30);
ALTER TABLE "monsoon$dev"."BillingInfo" ALTER COLUMN "id" SET DATA TYPE character varying(30);
ALTER TABLE "monsoon$dev"."BlogPost" ALTER COLUMN "id" SET DATA TYPE character varying(30);
ALTER TABLE "monsoon$dev"."BlogPost" ALTER COLUMN "image" SET DATA TYPE character varying(30);
ALTER TABLE "monsoon$dev"."BottomSize" ALTER COLUMN "id" SET DATA TYPE character varying(30);
ALTER TABLE "monsoon$dev"."Brand" ALTER COLUMN "id" SET DATA TYPE character varying(30);
ALTER TABLE "monsoon$dev"."Brand" ALTER COLUMN "logoImage" SET DATA TYPE character varying(30);
ALTER TABLE "monsoon$dev"."Brand" ALTER COLUMN "shopifyShop" SET DATA TYPE character varying(30);
ALTER TABLE "monsoon$dev"."Category" ALTER COLUMN "id" SET DATA TYPE character varying(30);
ALTER TABLE "monsoon$dev"."Collection" ALTER COLUMN "id" SET DATA TYPE character varying(30);
ALTER TABLE "monsoon$dev"."Color" ALTER COLUMN "id" SET DATA TYPE character varying(30);
ALTER TABLE "monsoon$dev"."Customer" ALTER COLUMN "id" SET DATA TYPE character varying(30);
ALTER TABLE "monsoon$dev"."Customer" ALTER COLUMN "admissions" SET DATA TYPE character varying(30);
ALTER TABLE "monsoon$dev"."Customer" ALTER COLUMN "billingInfo" SET DATA TYPE character varying(30);
ALTER TABLE "monsoon$dev"."Customer" ALTER COLUMN "detail" SET DATA TYPE character varying(30);
ALTER TABLE "monsoon$dev"."Customer" ALTER COLUMN "referrer" SET DATA TYPE character varying(30);
ALTER TABLE "monsoon$dev"."Customer" ALTER COLUMN "user" SET DATA TYPE character varying(30);
ALTER TABLE "monsoon$dev"."Customer" ALTER COLUMN "utm" SET DATA TYPE character varying(30);
ALTER TABLE "monsoon$dev"."CustomerAdmissionsData" ALTER COLUMN "id" SET DATA TYPE character varying(30);
ALTER TABLE "monsoon$dev"."CustomerDetail" ALTER COLUMN "id" SET DATA TYPE character varying(30);
ALTER TABLE "monsoon$dev"."CustomerDetail" ALTER COLUMN "shippingAddress" SET DATA TYPE character varying(30);
ALTER TABLE "monsoon$dev"."CustomerDetail" ALTER COLUMN "stylePreferences" SET DATA TYPE character varying(30);
ALTER TABLE "monsoon$dev"."CustomerMembership" ALTER COLUMN "id" SET DATA TYPE character varying(30);
ALTER TABLE "monsoon$dev"."CustomerMembership" ALTER COLUMN "customer" SET DATA TYPE character varying(30);
ALTER TABLE "monsoon$dev"."CustomerMembership" ALTER COLUMN "plan" SET DATA TYPE character varying(30);
ALTER TABLE "monsoon$dev"."CustomerMembership" ALTER COLUMN "subscription" SET DATA TYPE character varying(30);
ALTER TABLE "monsoon$dev"."CustomerMembershipSubscriptionData" ALTER COLUMN "id" SET DATA TYPE character varying(30);
ALTER TABLE "monsoon$dev"."CustomerNotificationBarReceipt" ALTER COLUMN "id" SET DATA TYPE character varying(30);
ALTER TABLE "monsoon$dev"."EmailReceipt" ALTER COLUMN "id" SET DATA TYPE character varying(30);
ALTER TABLE "monsoon$dev"."EmailReceipt" ALTER COLUMN "user" SET DATA TYPE character varying(30);
ALTER TABLE "monsoon$dev"."FitPic" ALTER COLUMN "id" SET DATA TYPE character varying(30);
ALTER TABLE "monsoon$dev"."FitPic" ALTER COLUMN "image" SET DATA TYPE character varying(30);
ALTER TABLE "monsoon$dev"."FitPic" ALTER COLUMN "location" SET DATA TYPE character varying(30);
ALTER TABLE "monsoon$dev"."FitPic" ALTER COLUMN "user" SET DATA TYPE character varying(30);
ALTER TABLE "monsoon$dev"."FitPicReport" ALTER COLUMN "id" SET DATA TYPE character varying(30);
ALTER TABLE "monsoon$dev"."FitPicReport" ALTER COLUMN "reported" SET DATA TYPE character varying(30);
ALTER TABLE "monsoon$dev"."FitPicReport" ALTER COLUMN "reporter" SET DATA TYPE character varying(30);
ALTER TABLE "monsoon$dev"."Image" ALTER COLUMN "id" SET DATA TYPE character varying(30);
ALTER TABLE "monsoon$dev"."InterestedUser" ALTER COLUMN "id" SET DATA TYPE character varying(30);
ALTER TABLE "monsoon$dev"."Label" ALTER COLUMN "id" SET DATA TYPE character varying(30);
ALTER TABLE "monsoon$dev"."Launch" ALTER COLUMN "id" SET DATA TYPE character varying(30);
ALTER TABLE "monsoon$dev"."Launch" ALTER COLUMN "brand" SET DATA TYPE character varying(30);
ALTER TABLE "monsoon$dev"."Launch" ALTER COLUMN "collection" SET DATA TYPE character varying(30);
ALTER TABLE "monsoon$dev"."Location" ALTER COLUMN "id" SET DATA TYPE character varying(30);
ALTER TABLE "monsoon$dev"."Location" ALTER COLUMN "user" SET DATA TYPE character varying(30);
ALTER TABLE "monsoon$dev"."Order" ALTER COLUMN "id" SET DATA TYPE character varying(30);
ALTER TABLE "monsoon$dev"."Order" ALTER COLUMN "customer" SET DATA TYPE character varying(30);
ALTER TABLE "monsoon$dev"."Order" ALTER COLUMN "sentPackage" SET DATA TYPE character varying(30);
ALTER TABLE "monsoon$dev"."OrderLineItem" ALTER COLUMN "id" SET DATA TYPE character varying(30);
ALTER TABLE "monsoon$dev"."Package" ALTER COLUMN "id" SET DATA TYPE character varying(30);
ALTER TABLE "monsoon$dev"."Package" ALTER COLUMN "fromAddress" SET DATA TYPE character varying(30);
ALTER TABLE "monsoon$dev"."Package" ALTER COLUMN "shippingLabel" SET DATA TYPE character varying(30);
ALTER TABLE "monsoon$dev"."Package" ALTER COLUMN "toAddress" SET DATA TYPE character varying(30);
ALTER TABLE "monsoon$dev"."PackageTransitEvent" ALTER COLUMN "id" SET DATA TYPE character varying(30);
ALTER TABLE "monsoon$dev"."PackageTransitEvent" ALTER COLUMN "package" SET DATA TYPE character varying(30);
ALTER TABLE "monsoon$dev"."PackageTransitEvent" ALTER COLUMN "reservation" SET DATA TYPE character varying(30);
ALTER TABLE "monsoon$dev"."PauseRequest" ALTER COLUMN "id" SET DATA TYPE character varying(30);
ALTER TABLE "monsoon$dev"."PauseRequest" ALTER COLUMN "membership" SET DATA TYPE character varying(30);
ALTER TABLE "monsoon$dev"."PaymentPlan" ALTER COLUMN "id" SET DATA TYPE character varying(30);
ALTER TABLE "monsoon$dev"."PhysicalProduct" ALTER COLUMN "id" SET DATA TYPE character varying(30);
ALTER TABLE "monsoon$dev"."PhysicalProduct" ALTER COLUMN "location" SET DATA TYPE character varying(30);
ALTER TABLE "monsoon$dev"."PhysicalProduct" ALTER COLUMN "price" SET DATA TYPE character varying(30);
ALTER TABLE "monsoon$dev"."PhysicalProduct" ALTER COLUMN "warehouseLocation" SET DATA TYPE character varying(30);
ALTER TABLE "monsoon$dev"."PhysicalProductPrice" ALTER COLUMN "id" SET DATA TYPE character varying(30);
ALTER TABLE "monsoon$dev"."PhysicalProductQualityReport" ALTER COLUMN "id" SET DATA TYPE character varying(30);
ALTER TABLE "monsoon$dev"."PhysicalProductQualityReport" ALTER COLUMN "physicalProduct" SET DATA TYPE character varying(30);
ALTER TABLE "monsoon$dev"."PhysicalProductQualityReport" ALTER COLUMN "user" SET DATA TYPE character varying(30);
ALTER TABLE "monsoon$dev"."Product" ALTER COLUMN "id" SET DATA TYPE character varying(30);
ALTER TABLE "monsoon$dev"."Product" ALTER COLUMN "brand" SET DATA TYPE character varying(30);
ALTER TABLE "monsoon$dev"."Product" ALTER COLUMN "category" SET DATA TYPE character varying(30);
ALTER TABLE "monsoon$dev"."Product" ALTER COLUMN "color" SET DATA TYPE character varying(30);
ALTER TABLE "monsoon$dev"."Product" ALTER COLUMN "modelSize" SET DATA TYPE character varying(30);
ALTER TABLE "monsoon$dev"."Product" ALTER COLUMN "season" SET DATA TYPE character varying(30);
ALTER TABLE "monsoon$dev"."Product" ALTER COLUMN "secondaryColor" SET DATA TYPE character varying(30);
ALTER TABLE "monsoon$dev"."Product" ALTER COLUMN "tier" SET DATA TYPE character varying(30);
ALTER TABLE "monsoon$dev"."ProductFunction" ALTER COLUMN "id" SET DATA TYPE character varying(30);
ALTER TABLE "monsoon$dev"."ProductMaterialCategory" ALTER COLUMN "id" SET DATA TYPE character varying(30);
ALTER TABLE "monsoon$dev"."ProductMaterialCategory" ALTER COLUMN "category" SET DATA TYPE character varying(30);
ALTER TABLE "monsoon$dev"."ProductModel" ALTER COLUMN "id" SET DATA TYPE character varying(30);
ALTER TABLE "monsoon$dev"."ProductNotification" ALTER COLUMN "id" SET DATA TYPE character varying(30);
ALTER TABLE "monsoon$dev"."ProductNotification" ALTER COLUMN "customer" SET DATA TYPE character varying(30);
ALTER TABLE "monsoon$dev"."ProductNotification" ALTER COLUMN "physicalProduct" SET DATA TYPE character varying(30);
ALTER TABLE "monsoon$dev"."ProductNotification" ALTER COLUMN "productVariant" SET DATA TYPE character varying(30);
ALTER TABLE "monsoon$dev"."ProductRequest" ALTER COLUMN "id" SET DATA TYPE character varying(30);
ALTER TABLE "monsoon$dev"."ProductRequest" ALTER COLUMN "user" SET DATA TYPE character varying(30);
ALTER TABLE "monsoon$dev"."ProductSeason" ALTER COLUMN "id" SET DATA TYPE character varying(30);
ALTER TABLE "monsoon$dev"."ProductSeason" ALTER COLUMN "internalSeason" SET DATA TYPE character varying(30);
ALTER TABLE "monsoon$dev"."ProductSeason" ALTER COLUMN "vendorSeason" SET DATA TYPE character varying(30);
ALTER TABLE "monsoon$dev"."ProductTier" ALTER COLUMN "id" SET DATA TYPE character varying(30);
ALTER TABLE "monsoon$dev"."ProductVariant" ALTER COLUMN "id" SET DATA TYPE character varying(30);
ALTER TABLE "monsoon$dev"."ProductVariant" ALTER COLUMN "color" SET DATA TYPE character varying(30);
ALTER TABLE "monsoon$dev"."ProductVariant" ALTER COLUMN "internalSize" SET DATA TYPE character varying(30);
ALTER TABLE "monsoon$dev"."ProductVariant" ALTER COLUMN "price" SET DATA TYPE character varying(30);
ALTER TABLE "monsoon$dev"."ProductVariantFeedback" ALTER COLUMN "id" SET DATA TYPE character varying(30);
ALTER TABLE "monsoon$dev"."ProductVariantFeedback" ALTER COLUMN "variant" SET DATA TYPE character varying(30);
ALTER TABLE "monsoon$dev"."ProductVariantFeedbackQuestion" ALTER COLUMN "id" SET DATA TYPE character varying(30);
ALTER TABLE "monsoon$dev"."ProductVariantPrice" ALTER COLUMN "id" SET DATA TYPE character varying(30);
ALTER TABLE "monsoon$dev"."ProductVariantWant" ALTER COLUMN "id" SET DATA TYPE character varying(30);
ALTER TABLE "monsoon$dev"."ProductVariantWant" ALTER COLUMN "productVariant" SET DATA TYPE character varying(30);
ALTER TABLE "monsoon$dev"."ProductVariantWant" ALTER COLUMN "user" SET DATA TYPE character varying(30);
ALTER TABLE "monsoon$dev"."PushNotificationReceipt" ALTER COLUMN "id" SET DATA TYPE character varying(30);
ALTER TABLE "monsoon$dev"."RecentlyViewedProduct" ALTER COLUMN "id" SET DATA TYPE character varying(30);
ALTER TABLE "monsoon$dev"."RecentlyViewedProduct" ALTER COLUMN "customer" SET DATA TYPE character varying(30);
ALTER TABLE "monsoon$dev"."RecentlyViewedProduct" ALTER COLUMN "product" SET DATA TYPE character varying(30);
ALTER TABLE "monsoon$dev"."Reservation" ALTER COLUMN "id" SET DATA TYPE character varying(30);
ALTER TABLE "monsoon$dev"."Reservation" ALTER COLUMN "customer" SET DATA TYPE character varying(30);
ALTER TABLE "monsoon$dev"."Reservation" ALTER COLUMN "lastLocation" SET DATA TYPE character varying(30);
ALTER TABLE "monsoon$dev"."Reservation" ALTER COLUMN "receipt" SET DATA TYPE character varying(30);
ALTER TABLE "monsoon$dev"."Reservation" ALTER COLUMN "returnedPackage" SET DATA TYPE character varying(30);
ALTER TABLE "monsoon$dev"."Reservation" ALTER COLUMN "sentPackage" SET DATA TYPE character varying(30);
ALTER TABLE "monsoon$dev"."Reservation" ALTER COLUMN "shippingOption" SET DATA TYPE character varying(30);
ALTER TABLE "monsoon$dev"."Reservation" ALTER COLUMN "user" SET DATA TYPE character varying(30);
ALTER TABLE "monsoon$dev"."ReservationFeedback" ALTER COLUMN "id" SET DATA TYPE character varying(30);
ALTER TABLE "monsoon$dev"."ReservationFeedback" ALTER COLUMN "reservation" SET DATA TYPE character varying(30);
ALTER TABLE "monsoon$dev"."ReservationFeedback" ALTER COLUMN "user" SET DATA TYPE character varying(30);
ALTER TABLE "monsoon$dev"."ReservationReceipt" ALTER COLUMN "id" SET DATA TYPE character varying(30);
ALTER TABLE "monsoon$dev"."ReservationReceiptItem" ALTER COLUMN "id" SET DATA TYPE character varying(30);
ALTER TABLE "monsoon$dev"."ReservationReceiptItem" ALTER COLUMN "product" SET DATA TYPE character varying(30);
ALTER TABLE "monsoon$dev"."Season" ALTER COLUMN "id" SET DATA TYPE character varying(30);
ALTER TABLE "monsoon$dev"."ShippingMethod" ALTER COLUMN "id" SET DATA TYPE character varying(30);
ALTER TABLE "monsoon$dev"."ShippingOption" ALTER COLUMN "id" SET DATA TYPE character varying(30);
ALTER TABLE "monsoon$dev"."ShippingOption" ALTER COLUMN "destination" SET DATA TYPE character varying(30);
ALTER TABLE "monsoon$dev"."ShippingOption" ALTER COLUMN "origin" SET DATA TYPE character varying(30);
ALTER TABLE "monsoon$dev"."ShippingOption" ALTER COLUMN "shippingMethod" SET DATA TYPE character varying(30);
ALTER TABLE "monsoon$dev"."ShopifyProductVariant" ALTER COLUMN "id" SET DATA TYPE character varying(30);
ALTER TABLE "monsoon$dev"."ShopifyProductVariant" ALTER COLUMN "brand" SET DATA TYPE character varying(30);
ALTER TABLE "monsoon$dev"."ShopifyProductVariant" ALTER COLUMN "image" SET DATA TYPE character varying(30);
ALTER TABLE "monsoon$dev"."ShopifyProductVariant" ALTER COLUMN "productVariant" SET DATA TYPE character varying(30);
ALTER TABLE "monsoon$dev"."ShopifyProductVariant" ALTER COLUMN "shop" SET DATA TYPE character varying(30);
ALTER TABLE "monsoon$dev"."ShopifyProductVariantSelectedOption" ALTER COLUMN "id" SET DATA TYPE character varying(30);
ALTER TABLE "monsoon$dev"."ShopifyShop" ALTER COLUMN "id" SET DATA TYPE character varying(30);
ALTER TABLE "monsoon$dev"."ShopifyShop_scope" ALTER COLUMN "nodeId" SET DATA TYPE character varying(30);
ALTER TABLE "monsoon$dev"."Size" ALTER COLUMN "id" SET DATA TYPE character varying(30);
ALTER TABLE "monsoon$dev"."Size" ALTER COLUMN "bottom" SET DATA TYPE character varying(30);
ALTER TABLE "monsoon$dev"."Size" ALTER COLUMN "top" SET DATA TYPE character varying(30);
ALTER TABLE "monsoon$dev"."SmsReceipt" ALTER COLUMN "id" SET DATA TYPE character varying(30);
ALTER TABLE "monsoon$dev"."StylePreferences" ALTER COLUMN "id" SET DATA TYPE character varying(30);
ALTER TABLE "monsoon$dev"."SyncTiming" ALTER COLUMN "id" SET DATA TYPE character varying(30);
ALTER TABLE "monsoon$dev"."Tag" ALTER COLUMN "id" SET DATA TYPE character varying(30);
ALTER TABLE "monsoon$dev"."TopSize" ALTER COLUMN "id" SET DATA TYPE character varying(30);
ALTER TABLE "monsoon$dev"."User" ALTER COLUMN "id" SET DATA TYPE character varying(30);
ALTER TABLE "monsoon$dev"."User" ALTER COLUMN "deviceData" SET DATA TYPE character varying(30);
ALTER TABLE "monsoon$dev"."User" ALTER COLUMN "pushNotification" SET DATA TYPE character varying(30);
ALTER TABLE "monsoon$dev"."UserDeviceData" ALTER COLUMN "id" SET DATA TYPE character varying(30);
ALTER TABLE "monsoon$dev"."UserPushNotification" ALTER COLUMN "id" SET DATA TYPE character varying(30);
ALTER TABLE "monsoon$dev"."UserPushNotificationInterest" ALTER COLUMN "id" SET DATA TYPE character varying(30);
ALTER TABLE "monsoon$dev"."UserPushNotificationInterest" ALTER COLUMN "user" SET DATA TYPE character varying(30);
ALTER TABLE "monsoon$dev"."UTMData" ALTER COLUMN "id" SET DATA TYPE character varying(30);
ALTER TABLE "monsoon$dev"."WarehouseLocation" ALTER COLUMN "id" SET DATA TYPE character varying(30);
ALTER TABLE "monsoon$dev"."WarehouseLocationConstraint" ALTER COLUMN "id" SET DATA TYPE character varying(30);
ALTER TABLE "monsoon$dev"."WarehouseLocationConstraint" ALTER COLUMN "category" SET DATA TYPE character varying(30);
